# Generated by Django 4.1.7 on 2023-07-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
